.TH DRAGONFLYWM 1 DragonflyWM
.SH NAME
DragonflyWM \- a nimble, fast and modern tiling window manager
.SH SYNOPSIS
.B dragonflywm
.RB [ \-v ]
.SH DESCRIPTION
.I DragonflyWM
is a nimble, fast and modern tiling window manager for X, based on
.BR MonsterWM.
Its goal is to be (somewhat) EWMH compliant and thus to deliver you with a modern tiling environment. Currently,
.I DragonflyWM
supports third party panels, pagers and window switchers. Some of this is rudimentary, but as the project matures support will be improved.
.P
.SH OPTIONS
.TP
.B \-v
Prints the version information to standard output, then exits.
.P
.SH MODES
.I DragonflyWM
comes with four tiling layouts by default plus the floating mode.
It allows the usual method of tiling window managers with the new window as
the master window, but it also provides the ability to have the new window opened
as the last window (at the bottom) of the stack.
.P
The available modes:
.TP
.B Tile stack
Stacked clients are tiled on the right side of the master clients.
.TP
.B Bottom stack
Stacked clients are tiled at the bottom of the master clients.
.TP
.B Grid mode
All clients are tiled in a grid, equally sharing and dividing the available screen space.
.TP
.B Monocle mode
All clients take up the entire available screen space. Other clients are hidden behind the current shown client.
.TP
.B Floating mode
Clients can be moved and resized freely around the screen, like a stacking
window manager.
.SH CONFIGURATION
.I DragonflyWM
is configured by copying
.I config.def.h
to
.I config.h
and (re)compiling the source code.
Settings include:
.TP
.B panelhoriz
Whether the panel is horizontal or vertical.
.TP
.B toppanel
Whether the panel should be on the top or on bottom of the screen.
.TP
.B panelheight
How much space should be reserved for the panel. Set to
.B 0
to disable the panel completely.
.TP
.B focuscolor / unfocuscolor
The colors for the borders of focused and unfocused windows.
.TP
.B borderwidth
The width of the borders the clients have. Set to
.B 0
to disable borders.
.TP
.B uselessgap
The width of the gaps between clients. Set to
.B 0
to disable gaps.
.TP
.B follow_window
Whether to follow the window to the new desktop it moved to.
.TP
.B follow_mouse
Whether to focus the window the mouse just entered.
.TP
.B minwsz
The minimum window size allowed. Prevents over-resizing with
the mouse or the keyboard (e.g. when resizing the master area).
.TP
.B default_desktop
Which desktop to focus by default.
.P
Virtual desktops can be configured in the
.B DeskSettings
array. For every row, increase
.B DESKTOP
by one. The following options can be set:
.TP
.B Name
The (EWMH) name of the desktop.
.TP
.B Layout
The tiling layout to use. For supported layouts, see the
.I MODES
up in this manpage.
.TP
.B Mfact
Set the size of the master area that will be used by the master window.
.TP
.B Nmaster
The number of windows in the master area.
.TP
.B Show panel
Whether this desktop should reserve space for a panel.
.P
Users can set
.B rules
on applications, by matching their
.B class name
,
.B instance name
or
.B window title.
The rules can specify on which
.B desktop
the application should start (or
.B -1
to signify the current desktop), whether the
.B focus
should change to that desktop when the application starts
, whether the application should start on
.B floating
or tiled mode and if the application should
.B attach aside
(whether it should spawn as the master window or as the last stack window).
.SH USAGE
.SS Keyboard and mouse commands
All of
.I DragonflyWM's
commands can be customized by editing
.I config.h
and recompiling.
.P
The default keyboard-bindings include:
.TP
.B Mod1\-Ctrl\-b
Toggles the panel on and off.
.TP
.B Mod1\-space
Toggles the focused client floating.
.TP
.B Mod1\-u
Focus the window with an urgent hint and focus the appropriate desktop if needed.
.TP
.B Mod1\-q
Close focused window.
.TP
.B Mod1\-j
Focus next window.
.TP
.B Mod1\-k
Focus previous window.
.TP
.B Mod1\-]
Increase master area size.
.TP
.B Mod1\-[
Decrease master area size.
.TP
.B Mod1\-Shift\-[
Shrink the size of the first stack window.
.TP
.B Mod1\-Shift\-]
Grow the size of the first stack window.
.TP
.B Mod1\-Left
Focus the previous desktop.
.TP
.B Mod1\-Right
Focus the next desktop.
.TP
.B Mod1\-Shift\-Left
Focus the previous desktop that has clients open.
.TP
.B Mod1\-Shift\-Right
Focus the next desktop that has clients open.
.TP
.B Mod1\-Tab
Switch to the last selected desktop.
.TP
.B Mod1\-Return
Moves the focused client to/from the master area (tiled layouts only).
.TP
.B Mod1\-Down
Move the focused window down the stack.
.TP
.B Mod1\-Up
Move the focused window up the stack.
.TP
.B Mod1\-t
Sets the tiled layout.
.TP
.B Mod1\-m
Sets the monocle layout.
.TP
.B Mod1\-b
Sets the bottom stack layout.
.TP
.B Mod1\-g
Sets the grid layout.
.TP
.B Mod1\-f
Sets the floating layout.
.TP
.B Mod1\-Ctrl\-r
Quit with exit value 0 (useful for restarts of the wm).
.TP
.B Mod1\-Ctrl\-q
Quit with exit value 1 (differentiate quit from restart).
.TP
.B Mod1\-1
Start
.BR xterm (1).
.TP
.B Mod1\-r
Start
.BR dmenu (1).
.TP
.B MOD4\-{Down,Up,Right,Left} arrow
Move the current window to the corresponding direction.
.TP
.B MOD4\-Shift\-{Down,Up,Right,Left} arrow
Resize the current window to the corresponding direction.
.TP
.B Mod1\-F{1..n}
Move to the nth desktop. By default,
.I DragonflyWM
is configured with four desktops.
The setting
.B follow_window
in
.I config.h
defines whether the focus should be moved to
the new desktop the window moved to.
.TP
.B Mod1\-Shift\-F{1..n}
Move focused window to nth workspace.
.P
Mouse bindings work either with the root window or a client window. This enables the use for right-click menus, for example. The default mouse bindings include:
.TP
.B Button3 - on the root window
Start
.BR dmenu (1).
.TP
.B Mod1\-Button1 - on the client window
Dragging the mouse will move the selected window.
.TP
.B Mod1\-Button2 - on the client window
Toggles the selected client floating.
.TP
.B Mod1\-Button3 - on the client window
Dragging the mouse will resize the selected window.
.SH SEE ALSO
.BR monsterwm
.BR dmenu (1)
.BR xterm (1)
.SH BUGS
.I DragonflyWM
is under active development. Please report all bugs to the author.
.SH AUTHOR
Jente Hidskes <jthidskes at outlook dot com>
